on:
  push:
    paths:
      - 'dst/**'
    branches:
      - release

name: Deploy Site to AWS S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync HTML Files to S3
      id: sync-html-files
      run: |
        aws s3 sync ./dst s3://personal-site-stack-s3bucket-1iylqhzp1uxog --delete --content-type text/html --exclude "*resources/*"

    - name: Sync Resource Files to S3
      id: sync-resource-files
      run: |
        aws s3 sync ./dst/resources s3://personal-site-stack-s3bucket-1iylqhzp1uxog/resources --delete
